### ISSUE TITLE
  Failed to query outdated pool transaction: NodeErrorCategory:3, Network error

### ISSUE THREAD

**Issue by kamuluprashanth** [fw4spl-org/fw4spl#10]
I  compiled my crypto coin by using the command 

make then 
I started the daemon ./mycoind , daemon started successfuly

after that i created wallet by using 

./simplewallet from build/release/src at that time i got this error

please give me the solution

2018-Jul-20 15:25:32.440572 INFO    Retry in 5 seconds...
2018-Jul-20 15:25:37.441061 INFO    Removing outdated pool transactions...
2018-Jul-20 15:25:37.441529 DEBUG   Pool union size 0, intersection size 0
2018-Jul-20 15:25:37.442607 ERROR   Failed to query outdated pool transaction: NodeErrorCategory:3, Network error

**Comment by gKevin** [comment]
I believe you wanted to post your issue here : https://github.com/cryptonotefoundation/cryptonote

fw4spl is a framework for medical imaging, not for cryptocurrencies.
