### ISSUE TITLE
Makefile:151: recipe for target 'all' failed (Deepin)

### ISSUE THREAD

**Issue by jehud2** [fw4spl-org/fw4spl#13]
[  1%] Built target glad
[  2%] Built target media-playback
[ 22%] Built target libobs
[ 23%] Built target file-updater
[ 23%] Built target obs-frontend-api
[ 26%] Built target obs-scripting
[ 27%] Built target _obspython
[ 28%] Built target obslua
[ 31%] Built target libobs-opengl
[ 34%] Built target linux-capture
[ 35%] Built target linux-pulseaudio
[ 36%] Built target linux-v4l2
[ 37%] Built target linux-jack
[ 38%] Built target linux-alsa
[ 42%] Built target linux-decklink
[ 43%] Built target vlc-video
[ 44%] Built target image-source
[ 45%] Built target obs-x264
[ 46%] Built target obs-libfdk
[ 48%] Built target obs-ffmpeg
[ 49%] Built target obs-ffmpeg-mux
[ 50%] Building C object plugins/obs-outputs/CMakeFiles/obs-outputs.dir/librtmp/rtmp.c.o
In file included from /opt/obs-studio/plugins/obs-outputs/librtmp/rtmp_sys.h:85:0,
                 from /opt/obs-studio/plugins/obs-outputs/librtmp/rtmp.c:32:
/usr/include/mbedtls/net.h:29:2: warning: #warning "Deprecated header file: Superseded by mbedtls/net_sockets.h" [-Wcpp]
 #warning "Deprecated header file: Superseded by mbedtls/net_sockets.h"
  ^~~~~~~
In file included from /opt/obs-studio/plugins/obs-outputs/librtmp/handshake.h:107:0,
                 from /opt/obs-studio/plugins/obs-outputs/librtmp/rtmp.c:179:
/opt/obs-studio/plugins/obs-outputs/librtmp/dh.h: In function ‘DHComputeSharedSecretKey’:
/opt/obs-studio/plugins/obs-outputs/librtmp/dh.h:360:12: warning: variable ‘len’ set but not used [-Wunused-but-set-variable]
     size_t len;
            ^~~
In file included from /opt/obs-studio/plugins/obs-outputs/librtmp/rtmp.c:179:0:
/opt/obs-studio/plugins/obs-outputs/librtmp/handshake.h: In function ‘HMACsha256’:
/opt/obs-studio/plugins/obs-outputs/librtmp/handshake.h:311:18: warning: variable ‘digestLen’ set but not used [-Wunused-but-set-variable]
     unsigned int digestLen;
                  ^~~~~~~~~
In file included from /opt/obs-studio/plugins/obs-outputs/librtmp/rtmp.c:32:0:
/opt/obs-studio/plugins/obs-outputs/librtmp/rtmp.c: In function ‘RTMP_TLS_Accept’:
/opt/obs-studio/plugins/obs-outputs/librtmp/rtmp_sys.h:140:2: error: implicit declaration of function ‘mbedtls_ssl_conf_dh_param_bin’ [-Werror=implicit-function-declaration]
  mbedtls_ssl_conf_dh_param_bin(ctx->conf,\
  ^
/opt/obs-studio/plugins/obs-outputs/librtmp/rtmp.c:1016:5: note: in expansion of macro ‘TLS_server’
     TLS_server(srv_ctx, r->m_sb.sb_ssl);
     ^~~~~~~~~~
cc1: some warnings being treated as errors
plugins/obs-outputs/CMakeFiles/obs-outputs.dir/build.make:662: recipe for target 'plugins/obs-outputs/CMakeFiles/obs-outputs.dir/librtmp/rtmp.c.o' failed
make[2]: *** [plugins/obs-outputs/CMakeFiles/obs-outputs.dir/librtmp/rtmp.c.o] Error 1
CMakeFiles/Makefile2:1335: recipe for target 'plugins/obs-outputs/CMakeFiles/obs-outputs.dir/all' failed
make[1]: *** [plugins/obs-outputs/CMakeFiles/obs-outputs.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gKevin** [comment]
Didn't you mean to post this here : https://github.com/obsproject/obs-studio

This is a _deprecated_ framework for medical imaging.
